# Generated by Django 5.1.15 on 2026-09-30 18:33

import apps.core.crypto
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPlatform',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=32)),
                ('external_account_id', models.CharField(blank=True, max_length=128)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_avatar_url', models.URLField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Authorization expired'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_platforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token_enc', apps.core.crypto.EncryptedTextField()),
                ('refresh_token_enc', apps.core.crypto.EncryptedTextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('secret_blob_enc', apps.core.crypto.EncryptedTextField(blank=True)),
                ('connected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_token', to='platforms.connectedplatform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='connectedplatform',
            index=models.Index(fields=['user', 'platform'], name='platforms_c_user_id_2034b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedplatform',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'external_account_id'), name='uniq_user_platform_account'),
        ),
    ]
