# Generated by Django 5.1.15 on 2026-09-30 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Failed login'), ('logout', 'Logout'), ('register', 'Registration'), ('password_reset', 'Password reset'), ('2fa_enabled', '2FA enabled'), ('2fa_disabled', '2FA disabled'), ('platform_connected', 'Platform connected'), ('platform_disconnected', 'Platform disconnected'), ('token_refreshed', 'OAuth token refreshed'), ('token_expired', 'OAuth token expired'), ('stream_started', 'Stream started'), ('stream_stopped', 'Stream stopped'), ('moderator_invited', 'Moderator invited'), ('moderator_revoked', 'Moderator revoked'), ('role_changed', 'Role changed'), ('device_authorized', 'Device authorized'), ('device_revoked', 'Device revoked'), ('automation_stopped', 'All automation stopped'), ('data_exported', 'Data exported'), ('account_deleted', 'Account deleted'), ('comment_deleted', 'Comment deleted (privacy)'), ('webhook_rejected', 'Webhook rejected (signature)')], db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moderator_invite', 'New moderator invitation'), ('stream_started', 'Stream started'), ('stream_ended', 'Stream ended'), ('platform_disconnected', 'Platform disconnected'), ('stream_error', 'Stream error'), ('ai_moderation_alert', 'AI moderation alert'), ('important_comment', 'Important comment'), ('device_authorized', 'New device authorized'), ('security_event', 'Security event')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx')],
            },
        ),
    ]
