# Generated by Django 5.1.15 on 2026-09-30 18:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamClip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual button'), ('hotkey', 'Keyboard hotkey'), ('android', 'Android app'), ('hype_auto', 'Hype auto-clip'), ('api', 'API')], default='manual', max_length=12)),
                ('aspect', models.CharField(choices=[('original', 'Original aspect ratio'), ('vertical_916', 'Vertical 9:16 (Shorts / Reels)')], default='original', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lookback_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired (retention)')], db_index=True, default='queued', max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('trigger_window_start', models.DateTimeField(blank=True, null=True)),
                ('trigger_window_end', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
