# Generated by Django 5.1.15 on 2026-09-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clips', '0001_initial'),
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamclip',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='streams.stream'),
        ),
        migrations.AddIndex(
            model_name='streamclip',
            index=models.Index(fields=['stream', '-created_at'], name='clips_strea_stream__a37b23_idx'),
        ),
        migrations.AddIndex(
            model_name='streamclip',
            index=models.Index(fields=['status'], name='clips_strea_status_5bda6b_idx'),
        ),
        migrations.AddIndex(
            model_name='streamclip',
            index=models.Index(fields=['expires_at'], name='clips_strea_expires_63b273_idx'),
        ),
        migrations.AddConstraint(
            model_name='streamclip',
            constraint=models.CheckConstraint(condition=models.Q(('lookback_seconds__gte', 5), ('lookback_seconds__lte', 600)), name='clip_lookback_bounds'),
        ),
    ]
