# Generated by Django 5.1.15 on 2026-09-30 18:34

import apps.streams.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('just-chatting', 'Just Chatting'), ('gaming', 'Gaming'), ('music', 'Music'), ('sports', 'Sports'), ('news', 'News'), ('education', 'Education'), ('business', 'Business & Finance'), ('food', 'Food & Cooking'), ('travel', 'Travel'), ('tech', 'Tech')], max_length=40)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stream_thumbs/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10)),
                ('ingest_stream_id', models.CharField(db_index=True, default=apps.streams.models.default_ingest_stream_id, max_length=64, unique=True)),
                ('ai_mode', models.CharField(choices=[('off', 'Off'), ('approval', 'Approval mode'), ('automatic', 'Automatic mode')], default='approval', max_length=12)),
                ('bot_enabled', models.BooleanField(default=True)),
                ('automation_paused_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('starting', 'Starting'), ('live', 'Live'), ('ended', 'Ended'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connecting', 'Connecting'), ('live', 'Live'), ('warning', 'Warning'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=14)),
                ('status_detail', models.TextField(blank=True)),
                ('rtmp_url', models.CharField(blank=True, max_length=500)),
                ('stream_key_enc', models.TextField(blank=True)),
                ('viewer_stats', models.JSONField(blank=True, default=dict)),
                ('restream_job_id', models.CharField(blank=True, max_length=64)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platforms', to='platforms.connectedplatform')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_targets', to='streams.stream')),
            ],
            options={
                'verbose_name_plural': 'Stream platforms',
            },
        ),
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_concurrent_viewers', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_replies', models.PositiveIntegerField(default=0)),
                ('ai_responses_sent', models.PositiveIntegerField(default=0)),
                ('bot_responses_sent', models.PositiveIntegerField(default=0)),
                ('moderation_events', models.PositiveIntegerField(default=0)),
                ('health', models.JSONField(blank=True, default=dict)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='streams.stream')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['owner', '-created_at'], name='streams_str_owner_i_576dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['status'], name='streams_str_status_db4df2_idx'),
        ),
        migrations.AddConstraint(
            model_name='streamplatform',
            constraint=models.UniqueConstraint(fields=('stream', 'connection'), name='uniq_stream_platform_connection'),
        ),
    ]
